#!/bin/bash
# Per-head attention span sweep, all on flex block masks.
#
# Everything is held at the best config -- B=64, ga=4, 8276 it, warmup 444, warmdown 3555,
# lr 0.0018, seed 42 -- so the span allocation is the only variable. Reference numbers:
#
#   plain causal (12 global)                              3.379164   127.1 min
#   2x64 2x128 2x512 6x1024   (6 global, DENSE mask)      3.373024   158.2 min  -0.0061
#   2x64 2x128 2x256 2x512 4x1024 (4 global, flex)        3.374269   129.7 min  -0.0049
#   4x128 4x256 2x512 2x1024  (2 global, flex)            ~parity, killed at step 4204
#
# Global-head count looks like the governing variable, with an interior optimum near 6:
# restrict too few heads and nothing happens, restrict too many and capability is lost.
# The 256 tier added nothing. This sweep tests four things in order of value:
#
#   A  4x64 2x128 2x512 4x1024   what more narrow heads buy, at 4 global (requested)
#   B  2x64 2x128 2x512 6x1024   the best-known allocation on the CHEAP implementation --
#                                 previously only run on the dense mask. Also serves as the
#                                 flex-vs-dense control for an identical span set.
#   C  2x64 2x128 8x1024         the other side of the optimum: fewer restricted heads
#   D  4x128 2x512 6x1024        same shape as B with the two 64s widened to 128. Since the
#                                 flex block floor is 128, a 64 span costs what 128 costs
#                                 while seeing less -- this asks whether narrowness is doing
#                                 anything beyond being cheap.
#
# ~130 min each, ~8.7 h total. Do not edit this file while it is running: bash reads
# scripts incrementally and a mid-run edit will corrupt the remaining commands.
cd /home/ubuntu/NoCap-Test || exit 1
mkdir -p /home/ubuntu/NoCap-Test/logs

COMMON=(--input_bin "data/fineweb10B/fineweb_train_*.bin"
        --input_val_bin "data/fineweb10B/fineweb_val_*.bin"
        --output_dir pylog124M --model d12
        --batch_size 64 --sequence_length 1024 --grad_accumulation_steps 4
        --num_iterations 8276 --warmup_iters 444 --warmdown_iters 3555
        --val_loss_every 128 --val_batch_size 16
        --weight_decay 0.1 --learning_rate 0.0018
        --attn_mask_impl flex --seed 42 --log_wandb)

run () {
  local name=$1 spec=$2
  echo "=============================================================="
  echo ">>> START $name  spans '$spec'  $(date -u '+%H:%M UTC') / $(TZ=Europe/Zurich date '+%H:%M %Z')"
  echo "=============================================================="
  uv run torchrun --standalone --nproc_per_node=1 train_gpt2.py "${COMMON[@]}" \
    --attn_head_windows "$spec" 2>&1 | tee "/home/ubuntu/NoCap-Test/logs/span_$name.log"
  echo ">>> DONE $name rc=${PIPESTATUS[0]}  $(date -u '+%H:%M UTC')"
  sleep 20
}

run A_4x64      "0:64,1:64,2:64,3:64,4:128,5:128,6:512,7:512"
run B_6global   "0:64,1:64,2:128,3:128,4:512,5:512"
run C_8global   "0:64,1:64,2:128,3:128"
run D_128floor  "0:128,1:128,2:128,3:128,4:512,5:512"

echo ">>> SPAN SWEEP COMPLETE $(date -u '+%H:%M UTC')"
